apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    # to find all the pods
    matchLabels:
      app: tickets
  # Config of the pod
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        # Which container to look out for
        - name: tickets
          image: adityaajmera/tickets
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets'

# Create the tickets service -> sets up a cluster IP
# Cluster IPs enable communication between various pods inside a cluster
---
apiVersion: v1
kind: Service
# How to recognize where traffic should be directed
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      # Service runs on Port 3000
      port: 3000
      targetPort: 3000
